### ISSUE TITLE
Support all octant CLI options in airshipui

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#11]
As a user of airshipUI, I should be able to invoke the airshipui command using a superset of the command line options that are currently available on the underlying octant command. Currently the airshipui command exposes 6 command line options, two of which (--airshipconf and --kubeconfig) are implemented to integrate maximally with airshipctl. But there are about a dozen other octant options including --context, --namespace, that are not exposed. 
The full list of these can be obtained by using 'octant --help'
Note that some options are described as "[DEV]" and others are not. All should be implemented, but the priority should lie with those that are not marked "[DEV]"

This was migrated from [AIR-208](https://airship.atlassian.net/browse/AIR-208)

**Comment by soumitrakhuntia** [comment]
Planning to look into this.

**Comment by aschiefe** [comment]
I may accidentally solve for this one by solving this issue: https://github.com/airshipit/airshipui/issues/14

**Comment by dotNomad** [comment]
Closed by f884450fb0d4beaeaf678e5c1760c2c7d850f5fa
