### ISSUE TITLE
Feature Request: Filter topology

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#12]
As a user I need to filter the portion of the topology that is currently being displayed, restricting it to a specific site; the “slice” of data shown in the topology should then be restricted to that particular site

Prerequisite: #13 

Migrated from [AIR-223](https://airship.atlassian.net/browse/AIR-223)

**Comment by jezogwza** [comment]
Functionality on the Topology Manager for filtering the data been represented. Essentially this means the ability to filter by Labels, or Annotations, Or Group, or Kind, etc....

Specifically the way that Topology Manager would consume documents is : 

1.  airshipctl document pkg and airshipctl config to identify where to retrieve files from
2.  airshipctl document has a filter class
3. Topology Manager would refresh the data with proper document set

implies that topology manager has a way of asking for Filter criteria.

FYI :
Airshipctl patchsets working on the filter functionality : 

- https://review.opendev.org/#/c/704123
- https://review.opendev.org/#/c/697327
- https://review.opendev.org/#/c/705016 
- https://review.opendev.org/#/c/698658

**Comment by aschiefe** [comment]
Closed because we can navigate sub sections with the left hand pane
