### ISSUE TITLE
Feature Request: Create plugin to explore topology (YAML Explorer)

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#13]
Need the ability to navigate through graphical representation of the topology expressed in the YAML files. This UI should represent the relationships that exist between the various components of the topology, and should offer some way of visualizing the customization and layers that are present therein.
Depends on #9

**Comment by GarySmith** [comment]
Octant does not yet have the ability for plugins to supply their own html/JavaScript components, but that is in the works. In the mean time, there are are two components that currently are supported in Octant that may be explored: GraphViz and the Resource Viewer.

**Comment by alanmeadows** [comment]
One project that is tangential to this concept worth checking out is https://containership.github.io/konstellate-editor/

While this doesn't edit/explore existing YAML but allows you to create net-new but I think this is some of the way there as an idea. 

Code: https://github.com/containership/konstellate-editor/

**Comment by dotNomad** [comment]
This feels quite large. Perhaps we should move this under an Epic and have individual issues for the functionality we want for this plugin? So far I see view the topology, edit YAML files in said topology, and create YAML files. There are also a few other issues related to this plugin.

**Comment by lb4368** [comment]
I am turning this into an epic and will create other issues related to this as we break it down.

**Comment by aschiefe** [comment]
Completed by Matt's yaml explorer
