### ISSUE TITLE
Recreate route handler tests with new Request interface

### ISSUE THREAD

**Issue by dotNomad** [airshipit/airshipui#16]
With the merging of https://github.com/vmware-tanzu/octant/pull/645 there is now a possibility of testing the argoui plugin route handler function which was removed in e384d17be647bdfb7885801731b340d7872aa67b.

A sample plugin with tests was created as a part of the issue above which can be drawn from.

**Comment by aschiefe** [comment]
Looking at this I'm not sure what the goal of this is.  Is the goal of this issue to reinstate the code that was removed, write a mock argo ui plugin or something different?

**Comment by dotNomad** [comment]
The goal is to add to `argoui/register_test.go ` and test the route handling.  The Request interface needs to be a bit more complex due to the fetching of the Argo UI endpoint, and it wasn't possible to do this originally. Now it seems to be.

**Comment by aschiefe** [comment]
Please close this issue it is no longer relevant to the current design.
