### ISSUE TITLE
Use .Get instead of .List when obtaining argo-ui endpoint

### ISSUE THREAD

**Issue by dotNomad** [airshipit/airshipui#17]
I75d55dc9842ca03453be28d0b6bab9b7dfc63549 made a change to use Client.List to retrieve the argo-ui endpoint to avoid a grpc server error. With the closing of https://github.com/vmware-tanzu/octant/issues/540 due to https://github.com/vmware-tanzu/octant/pull/643 we can make that change back and simplify that code.

**Comment by dotNomad** [comment]
Have a commit for this when the change is pulled into an Octant version

**Comment by GarySmith** [comment]
That will be a nice change. Using .List was a hack to get around that octant bug, so I'm glad to see it was resolved.
