### ISSUE TITLE
Introduce Visibility and Manageability for CEPH/CSI or Storage in general

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipui#21]
Besides the  Kubernetes storage artifacts themselves which the **_Overview plugin_** addresses for the most part. Some gaps need to be addressed. 

Specifically this issue is about going beyond. 
For something like CEPH how can we allow for this functionality : 

Sunny day operational activities such as : 

- Cluster health check
- OSD status
- Ceph Pool status
- Ceph volume size and usage data
- Ceph replication status
- Ceph PVC backup
- Provide k8s PVC mapping with Ceph volume

**Comment by matthew-fuller** [comment]
It was decided that this functionality was best exposed through Ceph / Storage management dashboards (ceph-mgr dashboard module, openATTIC, etc.), and this work was completed with commit b2d6b1ee76.
