### ISSUE TITLE
Openstack Manageability or Information available on UI

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipui#22]
UI for Openstack will enable Operations to trigger a well defined  command set for Compute, Network, Identity, Image, Block Storage, Queueing service APIs together from within the UI .

Some examples of things we might want to allow them to do :

- View tenant quota details
- View Images
- View Volumes
- View VM status
- Troubleshoot VM startup issues
- Troubleshoot Heat stack issues
- View Users/project

In general the ask is for a plugin that integrates AirshipUI with Openstack API's, so we can then rationalize what explicit . functionality we want to expose via it.

Stories for this Epic:

- #24

**Comment by jezogwza** [comment]
Should just satisfy this by iframing horizon ?

**Comment by aschiefe** [comment]
Assign this to me please
