### ISSUE TITLE
Openstack CLI Go Library

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipui#24]
Identify Openstack GO library that can be used to build Openstack Plugin

Related to #22

**Comment by aschiefe** [comment]
Currently evaluating https://github.com/gophercloud/gophercloud

**Comment by aschiefe** [comment]
Have a [working version](https://review.opendev.org/#/c/712788/) up and going.  What sorts of things are we wanting to expose to the UI?  Basic summaries or more detailed setups?

**Comment by jezogwza** [comment]
Specifically these and some of the other issues where modeled after the function that https://opendev.org/airship/porthole have.

Goal here would be top satisfy the use cases that the openstack utility covers from .

_Utility container for Openstack shall enable Operations to trigger the command set for Compute, Network, Identity, Image, Block Storage, Queueing service APIs together from within a single shell with a uniform command structure. The access to Openstack shall be controlled through Openstack RBAC role assigned to the user. User will have to set the Openstack environment (openrc) in utility container to access the Openstack CLIs. __


Some examples functions that we could expose through this plugin :

- View tenant quota details
- View Images
- View Volumes
- View VM status
- Troubleshoot VM startup issues
- Troubleshoot Heat stack issues
- View Users/project

**Comment by aschiefe** [comment]
Assign this to me please
