### ISSUE TITLE
Database Operationability

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipui#26]
As database components become more align with operator framework, teh notion of expressing its configuration and intentions via CRD / CR will become the norm.

A Plugin or enhancements to this database CR, to introduce Database health management operationalizing is what this epic introduces.

Ability to interact with the database to :
- Shutdown
- Verify connectivity from a client point of view
- Database cli interactions

Specifically common databases in the infrastructure such as :  

- mysqlDb
- postgreDb
- mariaDb
 
The ability of a plugin to do this, might of course be impacted by the external exposure of the database.

**Comment by matthew-fuller** [comment]
If no one's actively working on this issue, I can take a stab at it...

**Comment by aschiefe** [comment]
Please assign this to Matt Fuller

**Comment by matthew-fuller** [comment]
I have a (mostly) working simple version that I'm still actively working on, but many questions about this issue have surfaced. Specifically:

- Is this plugin meant to show info only on databases within the cluster, or from anywhere that's accessible from the host running the UI? In just the Airship (i.e. ucp) namespace, or any?
- **Shutdown**: is it a common use case for an Airship operator to need to shut down the backing databases?
- **Verify connectivity from a client point of view**: What type of client, and from where? Current plugin design creates a port forward to the running db container to test connectivity. Will something like this suffice? Databases may not have exposed endpoints outside of cluster IP.
- **Database CLI interactions**: Is there additional functionality desired here beyond what's already possible (and very easy to do) using Octant's Terminal feature to the running db container?

**Comment by ak3216** [comment]
2.0 tag please

**Comment by aschiefe** [comment]
Not currently workable can reopen if needs be
