### ISSUE TITLE
What is the relationship between a Plugin Config and AirshipUI config

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipui#28]
How do we manage configuration amongst plugin?

- Some of it might apply to multiple plugins
- Some of it might be unique .to a plugin

Need to define and design the relationship between  these different configuration aspects : 

- Airship config
- Kubernetes config
- Plugin Config's

**Comment by aschiefe** [comment]
We may need some form of plugin manager that either gets the defaults for each configured plugin or reads in a unified config and doles out the correct information to each plugin.
