### ISSUE TITLE
Rework argo integration

### ISSUE THREAD

**Issue by aschiefe** [airshipit/airshipui#29]
Argo UI is currently an iframe plugin.  This has significant hurdles to being able to properly render an iframe across real or virtual network segments.  It should be reworked to allow for a more portable utilization of the web standards.

**Comment by aschiefe** [comment]
It may need to be a status only integration with a link to the actual argo ui for anything above and beyond status readouts.

**Comment by seaneagan** [comment]
At this point I don't think we have current plans to use Argo as part of core Airship, see [this issue](https://github.com/airshipit/airshipctl/issues/177), so I think this can be closed.

**Comment by seaneagan** [comment]
Or perhaps it could be repurposed for removing the Argo integration as desired, reopening for now.

**Comment by aschiefe** [comment]
This can (and has been) removed because the iframe implementation that was done is currently unworkable.  It however can be included as an electron plugin which is now standard for the project.
