### ISSUE TITLE
AirshipUI support for baremetal/image building operations

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipui#36]
As part of the end to end lifecycle management, provide users the ability to execute baremetal & image build operations through Airship UI. 
This will likely be dependent on airshipctl issues: [#246](https://github.com/airshipit/airshipctl/issues/246), [#248](https://github.com/airshipit/airshipctl/issues/248)

**Comment by ak3216** [comment]
Milestone: beta

**Comment by aschiefe** [comment]
Closed by phase executor being in the phase explorer
