### ISSUE TITLE
Phase Support via AirshipUI

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipui#37]
Users should have the ability to execute the various phase commands via AirshipUI.

The current command set includes: phase apply & phase render.

**Comment by aschiefe** [comment]
This is a little vague, could some more verbiage be put around what is meant by the terms phase apply and render, and if it is in fact possible for me to set my phaser to stun.

**Comment by aschiefe** [comment]
A phase explorer / executor has been included in the UI
