### ISSUE TITLE
Leverage Electron UI plugin support to provide access to LMA dashboards

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipui#38]
Leverage Electron's ability to integrate with existing product dashboards to provide support for Logging, Monitoring & Alerting. Users will be able to launch these dashboards from AirshipUI. This would include such elements as Grafana, ElasticSearch, FluentD, etc. (each may get its own issue).

**Comment by ak3216** [comment]
Milestone: betav1

**Comment by matthew-fuller** [comment]
Work completed with commit b2d6b1ee76.
