### ISSUE TITLE
Provide a path forward for  integration with co located dashboards mechanisms

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipui#47]
Airshipui should have a mechanism to initiate co-located dashboards. I.E.  Initiate dashboard process if, identified in the list of plugins, and proper information is found.

**Comment by lb4368** [comment]
Milestone: alphav1

**Comment by ak3216** [comment]
Completed, close.

**Comment by matthew-fuller** [comment]
Work was completed with commit b2d6b1ee76.
