### ISSUE TITLE
Airshipui module for Tenant Management

### ISSUE THREAD

**Issue by sb1975** [airshipit/airshipui#48]
As a tenant-admin (and other tenant users) I should have the ability to manage the tenant resources : 

- Manage the tenant users, roles, rolebindings
- Manage the tenant namespace resources - ResourceQuota, IPPools,etc

**Comment by aschiefe** [comment]
Design discussion needed possibly duplicate with #58

**Comment by lb4368** [comment]
This epic will be used to collect tenant-level issues for managing individual sub-clusters.

**Comment by jezogwza** [comment]
Close this, this feature was. tied t multitenancy defined as segregation of tenant using namespaces. Now that we use explicit cluster this is no longer necessary,
