### ISSUE TITLE
Document Topology:  Site-level Manifest Documents View/Modify

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipui#49]
As an operator I need to have the capability to view/modify site-level manifest so that I have a user-friendly view of rendered site documents and am able to customize site documents directly via the UI.

The operator will be able to view rendered manifests directly in the UI by phase.  The rendered view would show the rendered documents with all kustomizations/replacements processed.

The operator would be allowed to make site-level changes to the rendered phase that would be written back to a new or existing site-level document for use in kustomization and/or replacement changes to rendering.

**Comment by lb4368** [comment]
This is related to #9 .

**Comment by aschiefe** [comment]
Closed by Matt Fuller's phase patches
