### ISSUE TITLE
Feature Request: Site Manager

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#5]
Users should be able to see the status of their sites, including the basics like workflow summaries, document revisions, and machine provisioning status, as well as the basic health of a site (remains to be seen whether this requires logging, monitoring, and alerting integration to report back or whether it is simpler than that).

This issue was migrated from [AIR-59](https://airship.atlassian.net/browse/AIR-59)

**Comment by dotNomad** [comment]
This issue feels a bit vague about what it is asking for, and has the potential to be asking for a lot. I think this might need some refinement.

**Comment by aschiefe** [comment]
reference #41
