### ISSUE TITLE
Display Software Inventory

### ISSUE THREAD

**Issue by aschiefe** [airshipit/airshipui#55]
A user has requested the ability to see the software installed on a system, both physical & possibly within a pod.

The software is defined in a manifest and the UI could show a visual diff as well in some form of CMDB type operation.

**Comment by aschiefe** [comment]
Design call is needed, it is unclear which software inventory would shown, the pod, the host etc and how access would be gained to catalog and display data.

**Comment by jezogwza** [comment]
Not sure what this was ...
