### ISSUE TITLE
Feature Request: Airship branding for airshipui

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#6]
As an AirshipUI developer, I want a basic airship branding style to be part of the airship plugin that I can override in my own corporate packaging if desired. This should include putting the airship logo and title in the UI and at least a prototype of a different color scheme (the default can be the baseline Octant branding)

**Acceptance Criteria**

- When run with the airship plugin , the Octant UI has an an Airship logo and title
- scss or other style files necessary to provide a basic branding scheme are in place in the airshipui repo, possibly with the styles commented out to maintain the default color scheme by default
- Stretch Goal: Support the disablement of out of the box Octant features.  Not necessary today but in the future, Octant may add so much functionality that we drown out what we’re trying to provide users with the AirshipUI.
- CI should be updated to do basic validation of the airship branding
 
This issue was migrated from [AIR-175](https://airship.atlassian.net/browse/AIR-175)

**Comment by GarySmith** [comment]
This story will require a change to octant in order to complete, which is captured in the issue:  https://github.com/vmware-tanzu/octant/issues/269

**Comment by aschiefe** [comment]
Fixed by commit c73b5cd3e2c29a8056dfe545fa22ea456f0af952
