### ISSUE TITLE
Allow users to apply new Pod Security Policy to an existing cluster

### ISSUE THREAD

**Issue by sharathrrao** [airshipit/airshipui#60]
**Problem description (if applicable)**
Allow the administrator of a cluster to add a new Pod Security Policy via the GUI.

**Proposed change**
Utilizing the GUI, an authorized user should be able to "edit" the kubernetes cluster to add a Pod Security Policy.
This provides the administrator of the cluster to either restrict or relax the security policy once a cluster has been deployed with a default PSP. 

**Potential impacts**
Allows the user to modify security sensitive configuration based on the type of applications deployed in the cluster.

**Comment by jezogwza** [comment]
Kubernetes is deprecating this, so we will have a discussion on what should we do instead.
Closing this issue.

**Comment by sharathrrao** [comment]
What about replacing PSP with a custom admission controller till the Community sorts out the way forward. Is that feasible for users to provide some sort of input on that which can then be applied to the corresponding cluster?

**Comment by sharathrrao** [comment]
What about using OPA Gatekeeper to implement policies for pods?
