### ISSUE TITLE
Design: Document the airshipctl topology "document" API

### ISSUE THREAD

**Issue by GarySmith** [airshipit/airshipui#9]
As a prerequisite for developing the YAML explorer, we have to understand what that set of topology yaml documents looks like and how they will be inter-related. This task is really not specific to airshipui, and arguably should be a task for the airshipctl project.

It would be preferable to use GraphViz or some similar tool that permits the source for the diagram to be checked into the airshipui repo

It might be necessary to also consult the airship configuration in order to determine the parent directory in which the individual files are stored

Some useful links:
- [sig-airship-yaml notes](https://docs.google.com/document/d/16XSoNvSkEIZCZHCwecRa7dhX0QE5ToGDB9U7cShvzJk/edit)
- [treasuremap prototype](https://opendev.org/airship/treasuremap/src/branch/v2) with example documents and directory structure (currently devoid of content)

This was migrated from [AIR-212](https://airship.atlassian.net/browse/AIR-212) story and tasks.

**Comment by GarySmith** [comment]
This item is blocked until the topology API and some example yaml documents have been created, as well as how kustomize will fit into the picture. At this point it is still very vague.

**Comment by lb4368** [comment]
Should we treat this issue as more of an epic as we create more specific issues related to viewing/modifying the document topology?  So far have created #49 .   This also is related to feature issue #13 .

**Comment by aschiefe** [comment]
Superseded by Matt's YAML explorer can reopen if needs be
